### ISSUE TITLE
Question about initial setup

### ISSUE THREAD

**Issue by Son-Vegitto** [AllanOricil/esp32-mfa-authenticator#23]
@AllanOricil 

Hello, 

I am extremely new to ESP, but would love to get this project working on my end. So, please forgive any stupid questions. 

If I were to purchase ESP32-2432S028, plug it into my computer and follow the instructions from https://allanoricil.github.io/esp32-mfa-authenticator to install the latest build, would that essentially be all there is to this? Other than formatting an SD card with the config.yml and keys.txt?

I was getting confused with the "Dev Environment Requirements" and "How to build" sections and if those steps were only needed if the website was not used to install the latest build. 

Kindly let me know your thoughts - thank you!

**Comment by AllanOricil** [comment]
1. Install the drivers on your computer.
2. Insert the SD card with the required files into your ESP32
3. Connect the ESP32 to your computer over USB
4. Open the site using Google Chrome. Some browsers aren't supported.
5. Read the tutorial and the README before installing the build on your ESP32. Pay attention to the steps where it explains about the calibration of the touch sensor. If you don't calibrate it right during the first launch, when the board asks you, you will have power off ESP32, remove the SD card from the board, plug the SD Card in your computer, change `force_recalibration` in config.yml, save it, put the SD card back to your ESP32, connect the ESP32 to your computer, go to the install website, connect it to the board,  this time click on the logs button, finally reboot your board, and wait for the touch calibration messages appear again.
6. Now that you are aware you will be prompted to calibrate the touch right after flashing the code into your board. Go to the install website, and follow the tutorial. Again, be ready for the calibration step, otherwise you will have to follow the steps from step 5.

**Comment by Son-Vegitto** [comment]
@AllanOricil - your instructions are great and this is probably just me, as I have not done anything with an ESP32 yet. 

Additional questions: 
To clarify, in your response Step 1, the drivers you mean are the ones located here, right? https://www.silabs.com/developers/usb-to-uart-bridge-vcp-drivers
If so, once I install those, I can set up my SD card with the two needed files, insert the card into the ESP32 and connect it to the computer, followed by your build install website. 

Is that all correct?

**Comment by AllanOricil** [comment]
@Son-Vegitto I'm not sure if those drivers will work for you. I don't know your OS and processor architecture. Try it and tell me later. 👍

**Comment by AllanOricil** [comment]
@Son-Vegitto I saw that the site has drivers for other OS. Before installing those drivers, just plug the esp32 into your pc via USB, and check if it is recognized by opening my instal website, and the click on the start button to see if your browser can recognize the board. If it doesn't, then download the driver for your OS, and repeat the above steps. If that doesn't work, then Google esp32 driver and see if you find something that works for you. In my case, it worked after installing the driver for MacOS listed on that link.

**Comment by AllanOricil** [comment]
@Son-Vegitto you should try v0.13.0 
It now has a screen to help you configure the touch sensor upon first boot.
